---
apiVersion: v1
kind: Service
metadata:
  name: iron-ui-dashboard
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: iron-ui-dashboard
    port: 4000
    targetPort: 4000 
    protocol: TCP
  selector:
    app: iron-ui-dashboard

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iron-ui-dashboard
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: iron-ui-dashboard
        app: iron-ui-dashboard
    spec:
      containers:
      - name: iron-ui-dashboard
        image: iron/functions-ui 
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: iron-ui-config
              key: API_URL
        ports:
        - name: ui-port
          containerPort: 4000
          protocol: TCP
